### PR TITLE
Adding possibility to manage HOSTNAME paramete

### PR DESCRIPTION
**Pull request by nonflet**
Adding possibility to manage HOSTNAME parameter, if u need to check your domain on mail-server (for example with relay).
Very needed feature if u are using Amazon SES

### CODE REVIEW

**Comment by apsoto** [comment]
Hey,  are you willing to take on maintainer responsibilities?  My time is severely limited and don't have the bandwidth to test changes?

**Comment by nonflet** [comment]
mmm, no problem , i'm using this code in our project ....
2 lines :) no such big problem

**Comment by apsoto** [comment]
Make sure you have time to help out, then comment and introduce yourself on #37.  

Thanks

**Comment by nonflet** [comment]
Hey, no problem if anyone ask me about this feature, i can help as fast, as it possible.

**Comment by yourabi** [comment]
Merged. Thank you @nonflet

**Pull request closed without merging**
