### PR TITLE
Miscellaneous bugfixes and improvements

### PR DESCRIPTION
**Pull request by freerobby**
In addition to fixing the issue I filed, I add a few improvements:
- Custom configurable mail servers
- Make the monitrc definition more generic by allowing it to be accessed from third party cookbooks. This way, for instance, the riak cookbook can control the riak monit configuration, needing only to include the monit recipe.
- Provide a working init.d script for ubuntu 12. The one that ships is invalid bash: https://bugs.launchpad.net/ubuntu/+source/monit/+bug/993381 I put this in its own recipe so that it can be explicitly included or not used.

Each change is in its own commit, so feel free to cherry-pick if there is something you see that you don't like.

### CODE REVIEW

**Comment by cmer** [comment]
+1

**Comment by apsoto** [comment]
Hey guys, anyone feel like becoming a collaborator?  I'm really behind on getting this cookbook updated and I don't see myself having the time to do it in the near term

**Comment by freerobby** [comment]
@cmer It uses the DSL rather than a ruby hash. I can't say for sure without context, but I _think_ this is what you want:

```
monitrc "elasticsearch" do
    template_cookbook 'elasticsearch'
    template_source "elasticsearch_monit.html.erb" # Or whatever your source file is.
    variables (pidfile => "#{node.elasticsearch[:pid_path]}/#{node.elasticsearch[:node_name].to_s.gsub(/\W/, '_')}.pid"))
end
```

Here's an example from our internal riak cookbook.

```
# This is an optional recipe that provides monit monitoring of your riak node. Requires the monit cookbook.
include_recipe "monit::default"

monitrc "riak" do
  variables(
    :process_matching => node[:riak][:monit][:process_matching],
    :start_program => node[:riak][:monit][:start_program],
    :http_host => node[:riak][:monit][:http_host],
    :http_port => node[:riak][:monit][:http_port]
  )
  template_source "riak-monit.conf.erb"
  template_cookbook "riak"
end
```

Hope this helps; let me know if need further clarification.

**Comment by freerobby** [comment]
@apsoto I can become a collaborator if ubuntu 12 testing (complete staging environment on EC2) is sufficient for merging pull requests. I'm not sure what your testing regimen is at this point, but if that's good enough I'm happy to help.

**Comment by apsoto** [comment]
Thanks,

I've only tested on Ubuntu 10.04 LTS.  I suppose if you make sure you bump the version number so 10.04 folks can pin their versions in their environments that should be good enough.  Hopefully at some point I can catch up and try 10.04 testing when I next try to update my monit cookbooks.

Alex

**Comment by apsoto** [comment]
ok Robby, I've added you as a collaborator.  Let me know when you think things are 'good' and I'll publish to the cookbooks site.

**Comment by freerobby** [comment]
Thanks Alex. I'll try to take care of everything tonight.  

## 

Robby Grossman
@freerobby (http://twitter.com/freerobby)
http://rob.by (http://rob.by/)

**Comment by jjaffeux** [comment]
hi @freerobby, can you give status on this please ?

**Comment by freerobby** [comment]
@jjaffeux Sorry, I'm way behind on this. Merging this in and reviewing other things shortly.

**Comment by jjaffeux** [comment]
great thx

**Pull request merged**
