### PR TITLE
Fix for Ubuntu init script expectations

### PR DESCRIPTION
**Pull request by dje**
It appears Ubuntu changed monit's init script in the current release.

### CODE REVIEW

**Comment by michaelglass** [comment]
what does the START variable actually do?

**Comment by dje** [comment]
Enables monit to start in Ubuntu's case.

**Comment by apsoto** [comment]
Hey,  are you willing to take on maintainer responsibilities?  My time is severely limited and don't have the bandwidth to test changes?

**Comment by freerobby** [comment]
@dje Thanks for this. I ran into this earlier today and fixed it on master, so we should be good now.

**Pull request closed without merging**
