### PR TITLE
make ssh port a variable / secure mailserver auth

### PR DESCRIPTION
**Pull request by yourabi**
It is very common to run ssh on a non-standard port -- make this a variable.

Also add option of configuring security/encryption to mailserver authentication.

### CODE REVIEW

**Comment by yourabi** [comment]
Any thoughts on this? Hoping to get it merged and uploaded to the Opscode community site so I don't have to keep my own patched version.

**Comment by apsoto** [comment]
Hey,  are you willing to take on maintainer responsibilities?  My time is severely limited and don't have the bandwidth to test changes?

**Comment by yourabi** [comment]
Sure.

**Comment by apsoto** [comment]
Please see #37 and comment if interested.

**Comment by yourabi** [comment]
Since this no longer applies cleanly I'm going to close and reopen against HEAD.

**Pull request closed without merging**
