### PR TITLE
Add recipes for monitoring resque workers and a scheduler

### PR DESCRIPTION
**Pull request by anujbiyani**
Based on what you said [here](https://github.com/apsoto/monit/pull/19) it sounds like adding recipes for monitoring specific packages is something you'd rather avoid, but you're open to discussing it.

I think it's a good idea to support recipes like this for a couple reasons:
1. Allows the end-user to keep their monit stuff in a monit cookbook. If I want to use the monitrc definition, I have to write a recipe in my own cookbook that calls the definition and maybe supplies a template file. Then in the future if I ever change from monit to some other monitoring service, I have to remove code from multiple locations.
2. These recipes are sometimes useful to other people. In this specific case (resque), it's not rare for a Rails app to be using resque and monit; it'd be nice to also provide them with sane defaults.
3. Reduces the number of forks so that there's one canonical repo for all things monit.

On the flip side:
1. The burden of maintaining these recipes falls on you instead of on a fork or in a private repository.
2. This cookbook could grow to be quite large if a lot of different recipes are added.

### CODE REVIEW

**Comment by apsoto** [comment]
Hey,  are you willing to take on maintainer responsibilities?  My time is severely limited and don't have the bandwidth to test changes?

**Comment by anujbiyani** [comment]
Sorry I don't think I have enough time either, but it seems like you found maintainers!

**Comment by anujbiyani** [comment]
Rebased on master.

**Comment by anujbiyani** [comment]
Freshly rebased on master.

**Comment by yourabi** [comment]
Hi - could you please cleanup the foodcritic warnings... 

Thanks!

**Comment by anujbiyani** [comment]
Fixed! Hopefully Travis agrees =)

**Pull request merged**
