### PR TITLE
only set email alerts if node[:monit][:notify_email] is not nil (defaults to nil)

### PR DESCRIPTION
**Pull request by anujbiyani**
Sometimes (for example in test environments), I don't want Monit to send email alerts.

I also added tests with [ChefSpec](https://github.com/acrmp/chefspec); it's a cool RSpec-based unit-testing framework for cookbooks.

### CODE REVIEW

**Comment by gwhitelaw** [comment]
This would be pretty nifty!

**Comment by miry** [comment]
Why do we need to add more attributes? What do you think to check `node[:monit][:notify_email]`, if it is empty or nil don't setup alert?

**Comment by anujbiyani** [comment]
Hmm good point; I'll change it.

**Comment by anujbiyani** [comment]
I changed the default value of `node[:monit][:notify_email]` to be `nil`; I think this is okay because setting it to `notify@example.com` won't work anyway.

Also updated ChefSpec (relative to my first commit) and updated the syntax used in my specs.

Let me know if you want anything else changed, or my commits squashed, or ChefSpec removed.

**Comment by anujbiyani** [comment]
Rebased my branch on master.

**Comment by yourabi** [comment]
Hi @anujbiyani - could you please rebase again and I'll merge as soon as you do that.

**Comment by anujbiyani** [comment]
Rebased.

**Comment by yourabi** [comment]
Thanks!

**Pull request merged**
