### PR TITLE
Add name to metadata.rb

### PR DESCRIPTION
**Pull request by chulkilee**
Add name to metadata.rb explicitly - good for [Berkshelf](http://berkshelf.com/)

### CODE REVIEW

**Comment by gregsymons** [comment]
Also good for Chef 11.

**Comment by jdutton** [comment]
Can you please take this pull request and release 0.7.1?  This is blocking berkshelf users and the fix is trivial and safe.  Thx!

**Comment by apsoto** [comment]
sorry for the delay, I've been slammed.  Thanks for the nudge.

**Comment by jdutton** [comment]
I understand slammed.  Thanks for making the time, I really appreciate it!  :smile:

**Pull request merged**
